name: CI&CD

on:
  push:
    branches:
      - deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
            node-version: '18.x'

      - name: Dependent environment
        run: |
          npm i
          node process.js
      
      - name: Deploy
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWD }}
          uploads: |
            dist => ${{ secrets.TARGET }}
